
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 16;
  public static final int CHAR = 46;
  public static final int POR = 4;
  public static final int STR = 43;
  public static final int ENTERO = 39;
  public static final int MASUNARIO = 8;
  public static final int REPEAT = 23;
  public static final int INT = 44;
  public static final int NOIGUALDAD = 32;
  public static final int FOR = 28;
  public static final int CP = 13;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int IGUAL = 18;
  public static final int OR = 37;
  public static final int IGUALDAD = 31;
  public static final int CH = 42;
  public static final int DIV = 5;
  public static final int INCREMENTO = 9;
  public static final int CC = 17;
  public static final int IF = 26;
  public static final int EOF = 0;
  public static final int MAYOROIGUAL = 34;
  public static final int DECREMENTO = 10;
  public static final int error = 1;
  public static final int COMA = 20;
  public static final int JUST = 24;
  public static final int MENOS = 3;
  public static final int MENOR = 29;
  public static final int MOD = 6;
  public static final int IDENT = 41;
  public static final int MENOSUNARIO = 7;
  public static final int CLL = 15;
  public static final int MENOROIGUAL = 30;
  public static final int REAL = 40;
  public static final int MAYOR = 33;
  public static final int ELSE = 27;
  public static final int PUNTO = 19;
  public static final int WHILE = 22;
  public static final int FLOAT = 45;
  public static final int STRING = 47;
  public static final int ALL = 14;
  public static final int AP = 12;
  public static final int LENGTH = 38;
  public static final int PRINT = 21;
  public static final int DO = 25;
  public static final int PYC = 11;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "MENOSUNARIO",
  "MASUNARIO",
  "INCREMENTO",
  "DECREMENTO",
  "PYC",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "IGUAL",
  "PUNTO",
  "COMA",
  "PRINT",
  "WHILE",
  "REPEAT",
  "JUST",
  "DO",
  "IF",
  "ELSE",
  "FOR",
  "MENOR",
  "MENOROIGUAL",
  "IGUALDAD",
  "NOIGUALDAD",
  "MAYOR",
  "MAYOROIGUAL",
  "NOT",
  "AND",
  "OR",
  "LENGTH",
  "ENTERO",
  "REAL",
  "IDENT",
  "CH",
  "STR",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING"
  };
}

