
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 23;
  public static final int AC = 12;
  public static final int CHAR = 50;
  public static final int POR = 4;
  public static final int STR = 45;
  public static final int ENTERO = 41;
  public static final int XOR = 40;
  public static final int INT = 48;
  public static final int IMPLICA = 38;
  public static final int NOIGUALDAD = 32;
  public static final int FOR = 22;
  public static final int CP = 9;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int IGUAL = 14;
  public static final int OR = 37;
  public static final int IGUALDAD = 31;
  public static final int CH = 44;
  public static final int DIV = 5;
  public static final int CC = 13;
  public static final int IF = 20;
  public static final int BOOLEAN = 52;
  public static final int EOF = 0;
  public static final int MAYOROIGUAL = 34;
  public static final int TRUE = 46;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int MENOS = 3;
  public static final int EXISTS = 24;
  public static final int MENOR = 29;
  public static final int IDENT = 43;
  public static final int MENOSUNARIO = 6;
  public static final int CLL = 11;
  public static final int MENOROIGUAL = 30;
  public static final int FROM = 26;
  public static final int REAL = 42;
  public static final int MAYOR = 33;
  public static final int ELSE = 21;
  public static final int PUNTO = 15;
  public static final int TO = 27;
  public static final int WHILE = 18;
  public static final int FLOAT = 49;
  public static final int DOBLEIMPLICA = 39;
  public static final int STRING = 51;
  public static final int ALL = 10;
  public static final int FALSE = 47;
  public static final int AP = 8;
  public static final int PRINT = 17;
  public static final int LENGTH = 28;
  public static final int DO = 19;
  public static final int STEP = 25;
  public static final int PYC = 7;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MENOSUNARIO",
  "PYC",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "IGUAL",
  "PUNTO",
  "COMA",
  "PRINT",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "FOR",
  "FORALL",
  "EXISTS",
  "STEP",
  "FROM",
  "TO",
  "LENGTH",
  "MENOR",
  "MENOROIGUAL",
  "IGUALDAD",
  "NOIGUALDAD",
  "MAYOR",
  "MAYOROIGUAL",
  "NOT",
  "AND",
  "OR",
  "IMPLICA",
  "DOBLEIMPLICA",
  "XOR",
  "ENTERO",
  "REAL",
  "IDENT",
  "CH",
  "STR",
  "TRUE",
  "FALSE",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "BOOLEAN"
  };
}

