
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\003\000\002\004\004\000\002\004\007" +
    "\000\002\004\007\000\002\004\007\000\002\004\011\000" +
    "\002\004\007\000\002\004\011\000\002\004\013\000\002" +
    "\004\012\000\002\004\012\000\002\004\011\000\002\020" +
    "\002\000\002\021\002\000\002\004\007\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\004\000\002\005\005\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\005\000\002\005\010\000\002\005\006\000\002\005\005" +
    "\000\002\005\005\000\002\005\003\000\002\005\003\000" +
    "\002\005\006\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\004\000\002\012\003\000\002\012\003\000" +
    "\002\013\003\000\002\014\003\000\002\017\003\000\002" +
    "\017\003\000\002\017\003\000\002\017\003\000\002\010" +
    "\004\000\002\010\005\000\002\007\003\000\002\007\005" +
    "\000\002\011\007\000\002\011\011\000\002\015\005\000" +
    "\002\016\005\000\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\215\000\044\005\005\012\022\014\014\023\031\024" +
    "\012\025\023\026\020\030\034\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\044\004\uffe7\005\uffe7\006\uffe7\007\uffe7\011\uffe7" +
    "\013\uffe7\015\uffe7\017\uffe7\022\uffe7\031\uffe7\032\uffe7\033" +
    "\uffe7\034\uffe7\035\uffe7\036\uffe7\040\uffe7\041\uffe7\001\002" +
    "\000\030\005\005\012\022\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\046\002\001\005\005\012\022\014\014\023\031\024" +
    "\012\025\023\026\020\030\034\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\052\004\uffe6\005\uffe6\006\uffe6\007\uffe6\011\uffe6" +
    "\013\uffe6\015\uffe6\016\207\017\uffe6\020\206\021\205\022" +
    "\uffe6\031\uffe6\032\uffe6\033\uffe6\034\uffe6\035\uffe6\036\uffe6" +
    "\040\uffe6\041\uffe6\001\002\000\004\045\102\001\002\000" +
    "\006\013\uffcf\045\uffcf\001\002\000\004\012\201\001\002" +
    "\000\006\013\uffcd\045\uffcd\001\002\000\044\005\ufff2\012" +
    "\ufff2\014\ufff2\023\ufff2\024\ufff2\025\ufff2\026\ufff2\030\ufff2" +
    "\043\ufff2\044\ufff2\045\ufff2\046\ufff2\047\ufff2\050\ufff2\051" +
    "\ufff2\052\ufff2\053\ufff2\001\002\000\014\004\043\005\044" +
    "\006\046\007\045\011\173\001\002\000\044\004\uffe9\005" +
    "\uffe9\006\uffe9\007\uffe9\011\uffe9\013\uffe9\015\uffe9\017\uffe9" +
    "\022\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\035\uffe9\036" +
    "\uffe9\040\uffe9\041\uffe9\001\002\000\044\004\uffd1\005\uffd1" +
    "\006\uffd1\007\uffd1\011\uffd1\013\uffd1\015\uffd1\017\uffd1\022" +
    "\uffd1\031\uffd1\032\uffd1\033\uffd1\034\uffd1\035\uffd1\036\uffd1" +
    "\040\uffd1\041\uffd1\001\002\000\004\012\165\001\002\000" +
    "\044\004\uffe8\005\uffe8\006\uffe8\007\uffe8\011\uffe8\013\uffe8" +
    "\015\uffe8\017\uffe8\022\uffe8\031\uffe8\032\uffe8\033\uffe8\034" +
    "\uffe8\035\uffe8\036\uffe8\040\uffe8\041\uffe8\001\002\000\030" +
    "\005\005\012\022\043\033\044\035\045\007\046\017\047" +
    "\032\050\011\051\027\052\013\053\025\001\002\000\044" +
    "\005\005\012\022\014\014\023\031\024\012\025\023\026" +
    "\020\030\034\043\033\044\035\045\007\046\017\047\032" +
    "\050\011\051\027\052\013\053\025\001\002\000\044\004" +
    "\uffe0\005\uffe0\006\uffe0\007\uffe0\011\uffe0\013\uffe0\015\uffe0" +
    "\017\uffe0\022\153\031\uffe0\032\uffe0\033\uffe0\034\uffe0\035" +
    "\uffe0\036\uffe0\040\uffe0\041\uffe0\001\002\000\006\013\uffcc" +
    "\045\uffcc\001\002\000\050\002\ufffe\005\ufffe\012\ufffe\014" +
    "\ufffe\015\ufffe\023\ufffe\024\ufffe\025\ufffe\026\ufffe\030\ufffe" +
    "\043\ufffe\044\ufffe\045\ufffe\046\ufffe\047\ufffe\050\ufffe\051" +
    "\ufffe\052\ufffe\053\ufffe\001\002\000\006\013\uffce\045\uffce" +
    "\001\002\000\044\004\uffdf\005\uffdf\006\uffdf\007\uffdf\011" +
    "\uffdf\013\uffdf\015\uffdf\017\uffdf\022\uffdf\031\uffdf\032\uffdf" +
    "\033\uffdf\034\uffdf\035\uffdf\036\uffdf\040\uffdf\041\uffdf\001" +
    "\002\000\004\012\144\001\002\000\044\004\uffd0\005\uffd0" +
    "\006\uffd0\007\uffd0\011\uffd0\013\uffd0\015\uffd0\017\uffd0\022" +
    "\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\036\uffd0" +
    "\040\uffd0\041\uffd0\001\002\000\044\004\uffd3\005\uffd3\006" +
    "\uffd3\007\uffd3\011\uffd3\013\uffd3\015\uffd3\017\uffd3\022\uffd3" +
    "\031\uffd3\032\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\040" +
    "\uffd3\041\uffd3\001\002\000\004\012\040\001\002\000\044" +
    "\004\uffd2\005\uffd2\006\uffd2\007\uffd2\011\uffd2\013\uffd2\015" +
    "\uffd2\017\uffd2\022\uffd2\031\uffd2\032\uffd2\033\uffd2\034\uffd2" +
    "\035\uffd2\036\uffd2\040\uffd2\041\uffd2\001\002\000\004\002" +
    "\037\001\002\000\004\002\000\001\002\000\032\005\005" +
    "\011\041\012\022\043\033\044\035\045\007\046\017\047" +
    "\032\050\011\051\027\052\013\053\025\001\002\000\032" +
    "\005\005\012\053\037\052\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\014\004\043\005\044\006\046\007\045\011\047\001" +
    "\002\000\030\005\005\012\022\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\030\005\005\012\022\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\030\005\005\012\022\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\030\005\005\012\022\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\032\005\005\012\053\037\052\043\033\044\035" +
    "\045\007\046\017\047\032\050\011\051\027\052\013\053" +
    "\025\001\002\000\010\011\123\040\074\041\075\001\002" +
    "\000\026\004\043\005\044\006\046\007\045\031\063\032" +
    "\057\033\060\034\064\035\065\036\061\001\002\000\032" +
    "\005\005\012\053\037\052\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\032\005\005\012\053\037\052\043\033\044\035\045" +
    "\007\046\017\047\032\050\011\051\027\052\013\053\025" +
    "\001\002\000\006\013\103\045\102\001\002\000\010\013" +
    "\076\040\074\041\075\001\002\000\030\004\043\005\044" +
    "\006\046\007\045\013\062\031\063\032\057\033\060\034" +
    "\064\035\065\036\061\001\002\000\030\005\005\012\022" +
    "\043\033\044\035\045\007\046\017\047\032\050\011\051" +
    "\027\052\013\053\025\001\002\000\030\005\005\012\022" +
    "\043\033\044\035\045\007\046\017\047\032\050\011\051" +
    "\027\052\013\053\025\001\002\000\030\005\005\012\022" +
    "\043\033\044\035\045\007\046\017\047\032\050\011\051" +
    "\027\052\013\053\025\001\002\000\044\004\uffea\005\uffea" +
    "\006\uffea\007\uffea\011\uffea\013\uffea\015\uffea\017\uffea\022" +
    "\uffea\031\uffea\032\uffea\033\uffea\034\uffea\035\uffea\036\uffea" +
    "\040\uffea\041\uffea\001\002\000\030\005\005\012\022\043" +
    "\033\044\035\045\007\046\017\047\032\050\011\051\027" +
    "\052\013\053\025\001\002\000\030\005\005\012\022\043" +
    "\033\044\035\045\007\046\017\047\032\050\011\051\027" +
    "\052\013\053\025\001\002\000\030\005\005\012\022\043" +
    "\033\044\035\045\007\046\017\047\032\050\011\051\027" +
    "\052\013\053\025\001\002\000\022\004\043\005\044\006" +
    "\046\007\045\011\uffdb\013\uffdb\040\uffdb\041\uffdb\001\002" +
    "\000\022\004\043\005\044\006\046\007\045\011\uffdc\013" +
    "\uffdc\040\uffdc\041\uffdc\001\002\000\022\004\043\005\044" +
    "\006\046\007\045\011\uffd9\013\uffd9\040\uffd9\041\uffd9\001" +
    "\002\000\022\004\043\005\044\006\046\007\045\011\uffda" +
    "\013\uffda\040\uffda\041\uffda\001\002\000\022\004\043\005" +
    "\044\006\046\007\045\011\uffdd\013\uffdd\040\uffdd\041\uffdd" +
    "\001\002\000\022\004\043\005\044\006\046\007\045\011" +
    "\uffd8\013\uffd8\040\uffd8\041\uffd8\001\002\000\032\005\005" +
    "\012\053\037\052\043\033\044\035\045\007\046\017\047" +
    "\032\050\011\051\027\052\013\053\025\001\002\000\032" +
    "\005\005\012\053\037\052\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\012\011\uffd7\013\uffd7\040\uffd7\041\uffd7\001\002\000" +
    "\012\011\uffd5\013\uffd5\040\074\041\uffd5\001\002\000\012" +
    "\011\uffd6\013\uffd6\040\uffd6\041\uffd6\001\002\000\044\004" +
    "\uffcb\005\uffcb\006\uffcb\007\uffcb\011\uffcb\013\uffcb\015\uffcb" +
    "\017\uffcb\022\uffcb\031\uffcb\032\uffcb\033\uffcb\034\uffcb\035" +
    "\uffcb\036\uffcb\040\uffcb\041\uffcb\001\002\000\050\004\uffc9" +
    "\005\uffc9\006\uffc9\007\uffc9\011\uffc9\013\uffc9\015\uffc9\016" +
    "\106\017\uffc9\020\105\022\uffc9\031\uffc9\032\uffc9\033\uffc9" +
    "\034\uffc9\035\uffc9\036\uffc9\040\uffc9\041\uffc9\001\002\000" +
    "\030\005\005\012\022\043\033\044\035\045\007\046\017" +
    "\047\032\050\011\051\027\052\013\053\025\001\002\000" +
    "\044\004\uffde\005\uffde\006\uffde\007\uffde\011\uffde\013\uffde" +
    "\015\uffde\017\uffde\022\uffde\031\uffde\032\uffde\033\uffde\034" +
    "\uffde\035\uffde\036\uffde\040\uffde\041\uffde\001\002\000\030" +
    "\005\005\012\022\043\033\044\035\045\007\046\017\047" +
    "\032\050\011\051\027\052\013\053\025\001\002\000\004" +
    "\043\107\001\002\000\004\017\110\001\002\000\046\004" +
    "\uffc7\005\uffc7\006\uffc7\007\uffc7\011\uffc7\013\uffc7\015\uffc7" +
    "\017\uffc7\020\111\022\uffc7\031\uffc7\032\uffc7\033\uffc7\034" +
    "\uffc7\035\uffc7\036\uffc7\040\uffc7\041\uffc7\001\002\000\004" +
    "\014\112\001\002\000\030\005\005\012\022\043\033\044" +
    "\035\045\007\046\017\047\032\050\011\051\027\052\013" +
    "\053\025\001\002\000\044\004\uffc6\005\uffc6\006\uffc6\007" +
    "\uffc6\011\uffc6\013\uffc6\015\uffc6\017\uffc6\022\uffc6\031\uffc6" +
    "\032\uffc6\033\uffc6\034\uffc6\035\uffc6\036\uffc6\040\uffc6\041" +
    "\uffc6\001\002\000\006\015\117\022\116\001\002\000\016" +
    "\004\043\005\044\006\046\007\045\015\uffc3\022\uffc3\001" +
    "\002\000\030\005\005\012\022\043\033\044\035\045\007" +
    "\046\017\047\032\050\011\051\027\052\013\053\025\001" +
    "\002\000\044\004\uffc5\005\uffc5\006\uffc5\007\uffc5\011\uffc5" +
    "\013\uffc5\015\uffc5\017\uffc5\022\uffc5\031\uffc5\032\uffc5\033" +
    "\uffc5\034\uffc5\035\uffc5\036\uffc5\040\uffc5\041\uffc5\001\002" +
    "\000\016\004\043\005\044\006\046\007\045\015\uffc4\022" +
    "\uffc4\001\002\000\044\004\043\005\044\006\046\007\045" +
    "\011\uffc8\013\uffc8\015\uffc8\017\uffc8\022\uffc8\031\uffc8\032" +
    "\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8\040\uffc8\041\uffc8" +
    "\001\002\000\012\011\uffd4\013\uffd4\040\uffd4\041\uffd4\001" +
    "\002\000\032\005\005\012\022\013\124\043\033\044\035" +
    "\045\007\046\017\047\032\050\011\051\027\052\013\053" +
    "\025\001\002\000\044\005\005\012\022\014\014\023\031" +
    "\024\012\025\023\026\020\030\034\043\033\044\035\045" +
    "\007\046\017\047\032\050\011\051\027\052\013\053\025" +
    "\001\002\000\014\004\043\005\044\006\046\007\045\013" +
    "\126\001\002\000\044\005\005\012\022\014\014\023\031" +
    "\024\012\025\023\026\020\030\034\043\033\044\035\045" +
    "\007\046\017\047\032\050\011\051\027\052\013\053\025" +
    "\001\002\000\052\002\ufff6\005\ufff6\012\ufff6\014\ufff6\015" +
    "\ufff6\023\ufff6\024\ufff6\025\ufff6\026\ufff6\027\ufff6\030\ufff6" +
    "\043\ufff6\044\ufff6\045\ufff6\046\ufff6\047\ufff6\050\ufff6\051" +
    "\ufff6\052\ufff6\053\ufff6\001\002\000\052\002\ufff4\005\ufff4" +
    "\012\ufff4\014\ufff4\015\ufff4\023\ufff4\024\ufff4\025\ufff4\026" +
    "\ufff4\027\ufff4\030\ufff4\043\ufff4\044\ufff4\045\ufff4\046\ufff4" +
    "\047\ufff4\050\ufff4\051\ufff4\052\ufff4\053\ufff4\001\002\000" +
    "\044\004\uffed\005\uffed\006\uffed\007\uffed\011\uffed\013\uffed" +
    "\015\uffed\017\uffed\022\uffed\031\uffed\032\uffed\033\uffed\034" +
    "\uffed\035\uffed\036\uffed\040\uffed\041\uffed\001\002\000\044" +
    "\004\uffec\005\uffec\006\uffec\007\uffec\011\uffec\013\uffec\015" +
    "\uffec\017\uffec\022\uffec\031\uffec\032\uffec\033\uffec\034\uffec" +
    "\035\uffec\036\uffec\040\uffec\041\uffec\001\002\000\044\004" +
    "\uffee\005\uffee\006\046\007\045\011\uffee\013\uffee\015\uffee" +
    "\017\uffee\022\uffee\031\uffee\032\uffee\033\uffee\034\uffee\035" +
    "\uffee\036\uffee\040\uffee\041\uffee\001\002\000\044\004\uffef" +
    "\005\uffef\006\046\007\045\011\uffef\013\uffef\015\uffef\017" +
    "\uffef\022\uffef\031\uffef\032\uffef\033\uffef\034\uffef\035\uffef" +
    "\036\uffef\040\uffef\041\uffef\001\002\000\010\011\136\040" +
    "\074\041\075\001\002\000\032\005\005\012\022\013\137" +
    "\043\033\044\035\045\007\046\017\047\032\050\011\051" +
    "\027\052\013\053\025\001\002\000\044\005\005\012\022" +
    "\014\014\023\031\024\012\025\023\026\020\030\034\043" +
    "\033\044\035\045\007\046\017\047\032\050\011\051\027" +
    "\052\013\053\025\001\002\000\014\004\043\005\044\006" +
    "\046\007\045\013\141\001\002\000\044\005\005\012\022" +
    "\014\014\023\031\024\012\025\023\026\020\030\034\043" +
    "\033\044\035\045\007\046\017\047\032\050\011\051\027" +
    "\052\013\053\025\001\002\000\052\002\ufff5\005\ufff5\012" +
    "\ufff5\014\ufff5\015\ufff5\023\ufff5\024\ufff5\025\ufff5\026\ufff5" +
    "\027\ufff5\030\ufff5\043\ufff5\044\ufff5\045\ufff5\046\ufff5\047" +
    "\ufff5\050\ufff5\051\ufff5\052\ufff5\053\ufff5\001\002\000\052" +
    "\002\ufff3\005\ufff3\012\ufff3\014\ufff3\015\ufff3\023\ufff3\024" +
    "\ufff3\025\ufff3\026\ufff3\027\ufff3\030\ufff3\043\ufff3\044\ufff3" +
    "\045\ufff3\046\ufff3\047\ufff3\050\ufff3\051\ufff3\052\ufff3\053" +
    "\ufff3\001\002\000\032\005\005\012\022\014\112\043\033" +
    "\044\035\045\007\046\017\047\032\050\011\051\027\052" +
    "\013\053\025\001\002\000\004\013\151\001\002\000\014" +
    "\004\043\005\044\006\046\007\045\013\147\001\002\000" +
    "\004\011\150\001\002\000\052\002\ufffc\005\ufffc\012\ufffc" +
    "\014\ufffc\015\ufffc\023\ufffc\024\ufffc\025\ufffc\026\ufffc\027" +
    "\ufffc\030\ufffc\043\ufffc\044\ufffc\045\ufffc\046\ufffc\047\ufffc" +
    "\050\ufffc\051\ufffc\052\ufffc\053\ufffc\001\002\000\004\011" +
    "\152\001\002\000\052\002\ufffb\005\ufffb\012\ufffb\014\ufffb" +
    "\015\ufffb\023\ufffb\024\ufffb\025\ufffb\026\ufffb\027\ufffb\030" +
    "\ufffb\043\ufffb\044\ufffb\045\ufffb\046\ufffb\047\ufffb\050\ufffb" +
    "\051\ufffb\052\ufffb\053\ufffb\001\002\000\004\045\155\001" +
    "\002\000\044\004\uffca\005\uffca\006\uffca\007\uffca\011\uffca" +
    "\013\uffca\015\uffca\017\uffca\022\uffca\031\uffca\032\uffca\033" +
    "\uffca\034\uffca\035\uffca\036\uffca\040\uffca\041\uffca\001\002" +
    "\000\046\004\uffc9\005\uffc9\006\uffc9\007\uffc9\011\uffc9\013" +
    "\uffc9\015\uffc9\017\uffc9\020\105\022\uffc9\031\uffc9\032\uffc9" +
    "\033\uffc9\034\uffc9\035\uffc9\036\uffc9\040\uffc9\041\uffc9\001" +
    "\002\000\004\024\157\001\002\000\004\012\160\001\002" +
    "\000\032\005\005\012\053\037\052\043\033\044\035\045" +
    "\007\046\017\047\032\050\011\051\027\052\013\053\025" +
    "\001\002\000\010\013\162\040\074\041\075\001\002\000" +
    "\004\011\163\001\002\000\052\002\ufff7\005\ufff7\012\ufff7" +
    "\014\ufff7\015\ufff7\023\ufff7\024\ufff7\025\ufff7\026\ufff7\027" +
    "\ufff7\030\ufff7\043\ufff7\044\ufff7\045\ufff7\046\ufff7\047\ufff7" +
    "\050\ufff7\051\ufff7\052\ufff7\053\ufff7\001\002\000\014\004" +
    "\043\005\044\006\046\007\045\013\062\001\002\000\032" +
    "\005\005\012\053\037\052\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\010\013\167\040\074\041\075\001\002\000\044\005" +
    "\005\012\022\014\014\023\031\024\012\025\023\026\020" +
    "\030\034\043\033\044\035\045\007\046\017\047\032\050" +
    "\011\051\027\052\013\053\025\001\002\000\052\002\ufffa" +
    "\005\ufffa\012\ufffa\014\ufffa\015\ufffa\023\ufffa\024\ufffa\025" +
    "\ufffa\026\ufffa\027\171\030\ufffa\043\ufffa\044\ufffa\045\ufffa" +
    "\046\ufffa\047\ufffa\050\ufffa\051\ufffa\052\ufffa\053\ufffa\001" +
    "\002\000\044\005\005\012\022\014\014\023\031\024\012" +
    "\025\023\026\020\030\034\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\052\002\ufff9\005\ufff9\012\ufff9\014\ufff9\015\ufff9\023" +
    "\ufff9\024\ufff9\025\ufff9\026\ufff9\027\ufff9\030\ufff9\043\ufff9" +
    "\044\ufff9\045\ufff9\046\ufff9\047\ufff9\050\ufff9\051\ufff9\052" +
    "\ufff9\053\ufff9\001\002\000\052\002\ufffd\005\ufffd\012\ufffd" +
    "\014\ufffd\015\ufffd\023\ufffd\024\ufffd\025\ufffd\026\ufffd\027" +
    "\ufffd\030\ufffd\043\ufffd\044\ufffd\045\ufffd\046\ufffd\047\ufffd" +
    "\050\ufffd\051\ufffd\052\ufffd\053\ufffd\001\002\000\044\005" +
    "\005\012\022\014\014\023\031\024\012\025\023\026\020" +
    "\030\034\043\033\044\035\045\007\046\017\047\032\050" +
    "\011\051\027\052\013\053\025\001\002\000\046\005\005" +
    "\012\022\014\014\015\ufff1\023\031\024\012\025\023\026" +
    "\020\030\034\043\033\044\035\045\007\046\017\047\032" +
    "\050\011\051\027\052\013\053\025\001\002\000\004\015" +
    "\200\001\002\000\050\002\uffff\005\uffff\012\uffff\014\uffff" +
    "\015\uffff\023\uffff\024\uffff\025\uffff\026\uffff\030\uffff\043" +
    "\uffff\044\uffff\045\uffff\046\uffff\047\uffff\050\uffff\051\uffff" +
    "\052\uffff\053\uffff\001\002\000\052\002\ufff0\005\ufff0\012" +
    "\ufff0\014\ufff0\015\ufff0\023\ufff0\024\ufff0\025\ufff0\026\ufff0" +
    "\027\ufff0\030\ufff0\043\ufff0\044\ufff0\045\ufff0\046\ufff0\047" +
    "\ufff0\050\ufff0\051\ufff0\052\ufff0\053\ufff0\001\002\000\032" +
    "\005\005\012\053\037\052\043\033\044\035\045\007\046" +
    "\017\047\032\050\011\051\027\052\013\053\025\001\002" +
    "\000\010\013\203\040\074\041\075\001\002\000\044\005" +
    "\005\012\022\014\014\023\031\024\012\025\023\026\020" +
    "\030\034\043\033\044\035\045\007\046\017\047\032\050" +
    "\011\051\027\052\013\053\025\001\002\000\052\002\ufff8" +
    "\005\ufff8\012\ufff8\014\ufff8\015\ufff8\023\ufff8\024\ufff8\025" +
    "\ufff8\026\ufff8\027\ufff8\030\ufff8\043\ufff8\044\ufff8\045\ufff8" +
    "\046\ufff8\047\ufff8\050\ufff8\051\ufff8\052\ufff8\053\ufff8\001" +
    "\002\000\004\042\216\001\002\000\032\005\005\012\022" +
    "\014\112\043\033\044\035\045\007\046\017\047\032\050" +
    "\011\051\027\052\013\053\025\001\002\000\030\005\005" +
    "\012\022\043\033\044\035\045\007\046\017\047\032\050" +
    "\011\051\027\052\013\053\025\001\002\000\014\004\043" +
    "\005\044\006\046\007\045\017\211\001\002\000\046\004" +
    "\uffe3\005\uffe3\006\uffe3\007\uffe3\011\uffe3\013\uffe3\015\uffe3" +
    "\017\uffe3\020\212\022\uffe3\031\uffe3\032\uffe3\033\uffe3\034" +
    "\uffe3\035\uffe3\036\uffe3\040\uffe3\041\uffe3\001\002\000\030" +
    "\005\005\012\022\043\033\044\035\045\007\046\017\047" +
    "\032\050\011\051\027\052\013\053\025\001\002\000\044" +
    "\004\043\005\044\006\046\007\045\011\uffe4\013\uffe4\015" +
    "\uffe4\017\uffe4\022\uffe4\031\uffe4\032\uffe4\033\uffe4\034\uffe4" +
    "\035\uffe4\036\uffe4\040\uffe4\041\uffe4\001\002\000\044\004" +
    "\uffe2\005\uffe2\006\uffe2\007\uffe2\011\uffe2\013\uffe2\015\uffe2" +
    "\017\uffe2\022\uffe2\031\uffe2\032\uffe2\033\uffe2\034\uffe2\035" +
    "\uffe2\036\uffe2\040\uffe2\041\uffe2\001\002\000\044\004\043" +
    "\005\044\006\046\007\045\011\uffe5\013\uffe5\015\uffe5\017" +
    "\uffe5\022\uffe5\031\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5" +
    "\036\uffe5\040\uffe5\041\uffe5\001\002\000\044\004\uffe1\005" +
    "\uffe1\006\uffe1\007\uffe1\011\uffe1\013\uffe1\015\uffe1\017\uffe1" +
    "\022\uffe1\031\uffe1\032\uffe1\033\uffe1\034\uffe1\035\uffe1\036" +
    "\uffe1\040\uffe1\041\uffe1\001\002\000\044\004\uffeb\005\uffeb" +
    "\006\uffeb\007\uffeb\011\uffeb\013\uffeb\015\uffeb\017\uffeb\022" +
    "\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\035\uffeb\036\uffeb" +
    "\040\uffeb\041\uffeb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\215\000\026\002\035\003\005\004\025\005\014\010" +
    "\023\011\027\012\015\013\020\014\003\017\007\001\001" +
    "\000\002\001\001\000\020\005\216\010\023\011\027\012" +
    "\015\013\020\014\003\017\007\001\001\000\022\004\176" +
    "\005\014\010\023\011\027\012\015\013\020\014\003\017" +
    "\007\001\001\000\002\001\001\000\004\007\100\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\173\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\005\163\010\023\011\027\012\015\013\020\014\003" +
    "\017\053\001\001\000\022\004\155\005\014\010\023\011" +
    "\027\012\015\013\020\014\003\017\007\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\005\041\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\022\005\050\006\134\010\023\011\027\012\015\013\020" +
    "\014\003\017\007\001\001\000\002\001\001\000\020\005" +
    "\133\010\023\011\027\012\015\013\020\014\003\017\007" +
    "\001\001\000\020\005\132\010\023\011\027\012\015\013" +
    "\020\014\003\017\007\001\001\000\020\005\131\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\020\005\130\010\023\011\027\012\015\013\020\014\003" +
    "\017\007\001\001\000\022\005\050\006\047\010\023\011" +
    "\027\012\015\013\020\014\003\017\007\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\005\050\006\121\010" +
    "\023\011\027\012\015\013\020\014\003\017\007\001\001" +
    "\000\022\005\055\006\054\010\023\011\027\012\015\013" +
    "\020\014\003\017\053\001\001\000\004\007\100\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\005\072\010" +
    "\023\011\027\012\015\013\020\014\003\017\007\001\001" +
    "\000\020\005\071\010\023\011\027\012\015\013\020\014" +
    "\003\017\007\001\001\000\020\005\070\010\023\011\027" +
    "\012\015\013\020\014\003\017\007\001\001\000\002\001" +
    "\001\000\020\005\067\010\023\011\027\012\015\013\020" +
    "\014\003\017\007\001\001\000\020\005\066\010\023\011" +
    "\027\012\015\013\020\014\003\017\007\001\001\000\020" +
    "\005\065\010\023\011\027\012\015\013\020\014\003\017" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\005\050\006\077\010\023\011\027\012\015" +
    "\013\020\014\003\017\007\001\001\000\022\005\050\006" +
    "\076\010\023\011\027\012\015\013\020\014\003\017\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\005\103" +
    "\010\023\011\027\012\015\013\020\014\003\017\007\001" +
    "\001\000\002\001\001\000\020\005\120\010\023\011\027" +
    "\012\015\013\020\014\003\017\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\015\112" +
    "\001\001\000\022\005\114\010\023\011\027\012\015\013" +
    "\020\014\003\016\113\017\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\005\117\010" +
    "\023\011\027\012\015\013\020\014\003\017\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\005\124\010\023\011\027\012\015" +
    "\013\020\014\003\017\007\001\001\000\022\004\127\005" +
    "\014\010\023\011\027\012\015\013\020\014\003\017\007" +
    "\001\001\000\002\001\001\000\022\004\126\005\014\010" +
    "\023\011\027\012\015\013\020\014\003\017\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\005\137\010\023\011\027\012\015\013" +
    "\020\014\003\017\007\001\001\000\022\004\142\005\014" +
    "\010\023\011\027\012\015\013\020\014\003\017\007\001" +
    "\001\000\002\001\001\000\022\004\141\005\014\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\005\145\010\023" +
    "\011\027\012\015\013\020\014\003\015\144\017\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\153\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\005\050\006" +
    "\160\010\023\011\027\012\015\013\020\014\003\017\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\005\050\006\165\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\002\001\001\000\022\004\167\005\014\010\023\011\027" +
    "\012\015\013\020\014\003\017\007\001\001\000\002\001" +
    "\001\000\022\004\171\005\014\010\023\011\027\012\015" +
    "\013\020\014\003\017\007\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\003\174\004\025\005\014\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\024\004\176\005\014\010\023\011\027\012\015\013\020" +
    "\014\003\017\007\021\175\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\005\050\006\201" +
    "\010\023\011\027\012\015\013\020\014\003\017\007\001" +
    "\001\000\002\001\001\000\022\004\203\005\014\010\023" +
    "\011\027\012\015\013\020\014\003\017\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\005\214\010\023" +
    "\011\027\012\015\013\020\014\003\015\213\017\007\001" +
    "\001\000\020\005\207\010\023\011\027\012\015\013\020" +
    "\014\003\017\007\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\005\212\010\023\011\027\012\015\013\020" +
    "\014\003\017\007\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // axioma ::= listaSentencia 
            {
              Object RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ls.ctd(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axioma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= axioma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listaSentencia ::= listaSentencia sentencia 
            {
              AST RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST l = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(l,s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencia",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaSentencia ::= sentencia 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(null,s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencia",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= expresion PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= PRINT AP expresion CP PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new PRINT(e,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= PRINT AP llavesArray CP PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new PRINT(e,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= IF AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 IF aux = new IF(c,s); RESULT = new IFELSE(aux,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= IF AP condicion CP sentencia ELSE sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sElseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sElseright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST sElse = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 IF aux = new IF(c,s); RESULT = new IFELSE(aux,sElse); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= WHILE AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WHILE(c,s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= DO sentencia WHILE AP condicion CP PYC 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new DOWHILE(s,c); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= FOR AP expresion PYC condicion PYC expresion CP sentencia 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                                                         /*    OBSERVACION:
                                                                                                                       En un FOR, tenemos                                                                                 
                                                                                                                       1. Una primera sentencia, que suele ser una variable i que se inicializa (i=1 por ejemplo)
                                                                                                                       2. La condición que debe cumplir dicha sentencia para entrar al bucle
                                                                                                                       3. Una actualización de la sentencia
                                                                                                                       4. Las sentencias a ejecutar dentro del bucle
                                                                                                         Lo podemos ver como un while(sentencia cumpla condición) -> ejecutar sentencias internas + actualizar sentencia 
                                                                                                  */

                                                                                                  AST sentenciasEjecutar = new AST (s, e2);        //donde s son las sentencias dentro del for y e2 la actualización de la variable
                                                                                                  WHILE whiLe = new WHILE(c, sentenciasEjecutar);  //recordamos que en WHILE había una condición para entrar y las sentencias de dentro
                                                                                                  RESULT = new AST(e1,whiLe);                      //En primer lugar se inicializa la variable y luego viene el WHILE construido que representa al FOR
                                                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= FOR AP PYC condicion PYC expresion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                                                  AST sentenciasEjecutar = new AST (s, e2);        //donde s son las sentencias dentro del for y e2 la actualización de la variable
                                                                                                  WHILE whiLe = new WHILE(c, sentenciasEjecutar);  //recordamos que en WHILE había una condición para entrar y las sentencias de dentro
                                                                                                  RESULT = new AST(null,whiLe);
                                                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= FOR AP expresion PYC condicion PYC CP sentencia 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                                                  AST sentenciasEjecutar = new AST (s, null);        //donde s son las sentencias dentro del for y e2 la actualización de la variable
                                                                                                  WHILE whiLe = new WHILE(c, sentenciasEjecutar);  //recordamos que en WHILE había una condición para entrar y las sentencias de dentro
                                                                                                  RESULT = new AST(e1,whiLe);
                                                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= FOR AP PYC condicion PYC CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		     AST sentenciasEjecutar = new AST (s, null);        //donde s son las sentencias dentro del for y e2 la actualización de la variable
                                                                                                  WHILE whiLe = new WHILE(c, sentenciasEjecutar);  //recordamos que en WHILE había una condición para entrar y las sentencias de dentro
                                                                                                  RESULT = new AST(null,whiLe);
                                                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$0 ::= 
            {
              AST RESULT =null;
 TablaSimbolos.nuevoBloque(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$1 ::= 
            {
              AST RESULT =(AST) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST l = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 TablaSimbolos.finBloque(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= ALL NT$0 listaSentencia NT$1 CLL 
            {
              AST RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (AST) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST l = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new BLOQUE(l); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= expresion MAS expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new SUMA(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion ::= expresion MENOS expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new RESTA(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion ::= expresion POR expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new POR(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= expresion DIV expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DIV(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= MENOS expresion 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new RESTA(e,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= AP expresion CP 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= numero 
            {
              AST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST n = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= caracter 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= string 
            {
              AST RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST st = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = st; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= IDENT 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  // Si la variable no ha sido declarada, emitimos un error
                                                    if(!TablaSimbolos.check(i)){
                                                        Generador.error(); 
                                                     } else {
                                                            int bloque = TablaSimbolos.inWhichBloque(i);
                                                            String nombre = i+"_"+bloque;
                                                            TIPO t = TablaSimbolos.getTipo(i);
                                                            RESULT = new CONSTANTE(nombre,t);
                                                     }      
                                                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= IDENT IGUAL expresion 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(!TablaSimbolos.check(i)){
                 /* x = expresion */                    Generador.error(); 
                                                     } else {
                                                        int bloque = TablaSimbolos.inWhichBloque(i);
                                                        String nombre = i+"_"+bloque;
                                                        RESULT = new ASIG(nombre, e);
                                                     }
                                                                 
                                                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= IDENT AC expresion CC IGUAL expresion 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(!TablaSimbolos.check(i)){
                 /*para los array: x[i] = expresion*/                 Generador.error(); 
                                                                  } else {
                                                                      int bloque = TablaSimbolos.inWhichBloque(i);
                                                                      String nombre = i+"_"+bloque;
                                                                      TIPO t = TablaSimbolos.getTipo(i);
                                                                      RESULT = new VECTORELEM(nombre,t,e1,e2);
                                                                  }

                                                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= IDENT AC expresion CC 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(!TablaSimbolos.check(i)){
                                                                      Generador.error(); 
                                                                  } else {
                                                                      int bloque = TablaSimbolos.inWhichBloque(i);
                                                                      String nombre = i+"_"+bloque;
                                                                      TIPO t = TablaSimbolos.getTipo(i);
                                                                      RESULT = new VECTORELEM(nombre,t,e,null);
                                                                  }
                                                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= IDENT IGUAL llavesArray 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(!TablaSimbolos.check(i)){
                /* x = {a,b,c...} */                                     Generador.error(); 
                                                                  } else {
                                                                         int bloque = TablaSimbolos.inWhichBloque(i);
                                                                         String nombre = i+"_"+bloque;
                                                                         RESULT = new ASIGARR(nombre,s);
                                                                  }
                                                                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= IDENT PUNTO LENGTH 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 if(!TablaSimbolos.check(i)){
                                                                      Generador.error(); 
                                                                  } else {
                                                                      int bloque = TablaSimbolos.inWhichBloque(i);
                                                                      String nombre = i+"_"+bloque;
                                                                      TIPO t = TablaSimbolos.getTipoSub(nombre);
                                                                      RESULT = new LEN(nombre,t);
                                                                  }
                                                                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= declaracion 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST d = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= decArray 
            {
              AST RESULT =null;
		int dAleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dAright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST dA = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = dA;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= AP tipo CP expresion 
            {
              AST RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CASTING(t,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion ::= expresion IGUALDAD expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(1,e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion ::= expresion NOIGUALDAD expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(2, e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion ::= expresion MAYOR expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(3,e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= expresion MAYOROIGUAL expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(4,e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicion ::= expresion MENOR expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(5,e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condicion ::= expresion MENOROIGUAL expresion 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST e1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONDICION(6,e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condicion ::= AP condicion CP 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condicion ::= condicion AND condicion 
            {
              AST RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST c1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST c2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AND(7, c1,c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // condicion ::= condicion OR condicion 
            {
              AST RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST c1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST c2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OR(8, c1,c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // condicion ::= NOT condicion 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST c = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NOT(9, c); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // numero ::= ENTERO 
            {
              AST RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONSTANTE(n,new TIPO(TIPO.INT)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("numero",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // numero ::= REAL 
            {
              AST RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONSTANTE(r,new TIPO(TIPO.FLOAT)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("numero",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // caracter ::= CH 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CONSTANTE(c,new TIPO(TIPO.CHAR)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("caracter",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // string ::= STR 
            {
              AST RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String st = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CADENA(st); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("string",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // tipo ::= INT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.INT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tipo ::= FLOAT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.FLOAT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // tipo ::= CHAR 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.CHAR); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // tipo ::= STRING 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.STRING); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // declaracion ::= tipo decVar 
            {
              AST RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST var = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                //varDeclarada será una CONSTANTE o ASIG, en cualquier caso, una EXPRESION
                                                                String nombreVar = ((EXP)var).getCodigo();
                                                                ((EXP)var).setTipo(t); 
                                                                TablaSimbolos.insertar(nombreVar,t);   
                                                                RESULT = new DEC(null,var);  
                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // declaracion ::= declaracion COMA decVar 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST d = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST var = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                String nombreVar = ((EXP)var).getCodigo();
                                                                TIPO t = ((DEC)d).getTipo();
                                                                ((EXP)var).setTipo(t);
                                                                TablaSimbolos.insertar(nombreVar,t);
                                                                RESULT = new DEC(d,var);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // decVar ::= IDENT 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 String nombre = TablaSimbolos.varBlock(i); RESULT = new CONSTANTE(nombre); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decVar",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // decVar ::= IDENT IGUAL expresion 
            {
              AST RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 String nombre = TablaSimbolos.varBlock(i); RESULT = new ASIG(nombre, e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decVar",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // decArray ::= tipo IDENT AC ENTERO CC 
            {
              AST RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 int tam = Integer.parseInt(n); 
                                                               TIPO tipo = new TIPO(TIPO.ARRAY,t,tam);
                                                               String nombre = TablaSimbolos.varBlock(i);
                                                               TablaSimbolos.insertar(nombre,tipo);
                                                               RESULT = new VECTOR(nombre,tipo); 
                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decArray",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // decArray ::= tipo IDENT AC ENTERO CC IGUAL llavesArray 
            {
              AST RESULT =null;
		int subtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int subtright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		TIPO subt = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                                      TIPO tipo = new TIPO(TIPO.ARRAY,subt,Integer.parseInt(n));
                                                                      String nombre = TablaSimbolos.varBlock(i);
                                                                      TablaSimbolos.insertar(nombre,tipo);
                                                                      RESULT = new ASIGARR(nombre,s);
                                                                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decArray",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // llavesArray ::= ALL listaArr CLL 
            {
              AST RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<AST> l = (ArrayList<AST>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new LISTARRAY(l); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("llavesArray",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // listaArr ::= listaArr COMA expresion 
            {
              ArrayList<AST> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<AST> l = (ArrayList<AST>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		     l.add(e);
                                                               RESULT = l;
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaArr",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // listaArr ::= expresion 
            {
              ArrayList<AST> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST e = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<AST> aux = new ArrayList<>(); 
                                                           aux.add(e);
                                                           RESULT = aux;
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaArr",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
